language: node_js
node_js:
  - "14"
dist: trusty
env:
  global:
    - JWT_SECRET='abcd'
cache:
  directories:
    - auth/node_modules
script:
  - cd auth
  - npm install
  - sleep 3
  - npm run test:ci