apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
stringData:
  STRIPE_SECRET: "sk_test_51IkApBKPuAe3CMG54tnKCNG3vKhd0lhzLkO8utHfoIHObfao9x9NZtgCd3w9uW9iBPdHABC8PA2G5K9hldowaR5200oLmwNx2j"