apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - name: tickets
        image: joker7nbt/ticketing-tickets
        env:
          - name: MONGO_URI
            value: 'mongodb://tickets-mongo-srv:27017/tickets'
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_SECRET
          - name: NATS_CLUSTER_ID
            value: 'ticketing'
          - name: NATS_CLIENT_ID
            value: 'ticket'
          - name: NATS_URL
            value: 'http://nats-srv:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
  - name: tickets
    protocol: TCP
    port: 3000
    targetPort: 3000

